### ISSUE TITLE
Server selection > It takes too long to restart the app with the incorrect server 

### ISSUE THREAD

**Issue by tlle14** [Twake/Mobile#295]
# Precondition
1. Set the incorrect server in the app
2. Close the app

# Actual Result
Reopen the app, it takes too long (about 1 min) to start the app and display the login screen
https://images.zenhubusercontent.com/309637937/50d79a5c-d779-4063-ba55-ddf5d3c5ec6d/video7702d785_43f1_4731_b06f_0794800f060cvideo.mp4

# Expected Result
It shouldn't take too long to start the app, no matter what the inputted server is

# Environment
Both Android and iOS app
Build version: twake.2.2.8

**Comment by bobs4462** [comment]
@tlle14 This issue is going to be solved in #68, because it's not really related to incorrect server, but rather a global application issue, which is related to amount of work the application does while booting, we will research the issue and try to minimize that work. This issue can be closed I think.

**Comment by tlle14** [comment]
Yes, this one is fixed
Thank @bobs4462 

https://user-images.githubusercontent.com/69950655/111098053-462db300-8575-11eb-8f32-51ffb7e73fc7.mp4
